# Generated by Django 4.1 on 2022-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_reign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reign',
        ),
    ]
