# Generated by Django 4.1 on 2022-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tag_alter_review_value_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
