# Generated by Django 4.1 on 2022-08-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Vote_ratio',
            new_name='vote_ratio',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
